SELECT LENGTH('SQL');
SELECT LOWER('SQL');
SELECT LEFT('SQL',2);
SELECT SUBSTRING('SQL',2,1);
SELECT CONCAT('SQL','-','FUNCTIONS');
SELECT 'SQL' ||'-'||'FUNCTIONS';
SELECT TRIM(' SQL');
SELECT REPLACE ('SQL','Q','_');
SELECT REGEXP_REPLACE ('data.tomerrot@gmail.com','^.(@)','\1');

SELECT NULLIF(20,10);
SELECT COALESCE(NULL,20,10);
